version: 2
plan:
  project-key: BOW
  name: Bowling
  key: BOW

stages:
  - Build Stage:
      jobs: 
        - Build 
  - Test Stage:
      jobs: 
        - Test

Build:
  tasks:
    - script:
        - echo 'Hello world !'
        
Test:
  tasks:
    - script: BowlingGame.Test/UnitTest1.cs
